apiVersion: apps/v1
kind: Deployment
metadata:
  name: f5-demo
  namespace: f5-demo
spec:
  selector:
    matchLabels:
      app: f5-demo
  replicas: 3
  template:
    metadata:
      labels:
        app: f5-demo
    spec:
      containers:
        - name: f5-demo
          image: f5devcentral/f5-hello-world:develop
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: f5-demo
  namespace: f5-demo
spec:
  selector:
    app: f5-demo
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
